### Import libraries

In [1]:
import pandas as pd
import glob
from nltk import word_tokenize, pos_tag, sent_tokenize

### Read the data

In [19]:
df = pd.read_csv('../data/civility/convo_data_with_moderation_scores.csv')

# Rename convo_turn for clarity
df['convo_turn'] = df['convo_turn'].apply(lambda x: "user_response_1" if x=="initial_opinion" else x)

# Convert string representation of dict back to dict
df['emotion_scores'] = df['emotion_scores'].apply(lambda x: eval(x))

# Agree vs Disagree
df['agree_disagree'] = "Agree"
df.loc[df['treatment'].apply(lambda x: "Disagree" in x), 'agree_disagree'] = "Disagree"

# Ingroup vs Outgroup
df['ingroup_outgroup'] = "Ingroup"
df.loc[df['treatment'].apply(lambda x: "Outgroup" in x), 'ingroup_outgroup'] = "Outgroup"

### go emotions BERT model outputs

In [20]:
list_of_emotions = [*df['emotion_scores'].iloc[0].keys()]

In [21]:
# take column of dicts and make each key a separate column within the dataframe
emotion_df = pd.json_normalize(df['emotion_scores'])
df = pd.concat([df, emotion_df], axis=1)

In [22]:
df['convo_turn'] = df['convo_turn'].apply(lambda x: {'initial_opinion':'user_response_1'}.get(x, x))

In [23]:
pivot_df = df[df['convo_turn'].apply(lambda x: 'user' in x.lower())].pivot_table(index='treatment', values=list_of_emotions, aggfunc='mean')

for emo in list_of_emotions:
    print(f"Emotion: {emo}")
    print(" \n".join([f"{i[0]}: {i[1]}" for i in pivot_df[emo].items()]))
    print()

Emotion: neutral
Ingroup Agree: 0.22486399783298183
Ingroup Disagree: 0.29680706973032145
Outgroup Agree: 0.2711841588392556
Outgroup Disagree: 0.3159952550737953

Emotion: approval
Ingroup Agree: 0.37377150512398466
Ingroup Disagree: 0.28969686093086827
Outgroup Agree: 0.3097653771026503
Outgroup Disagree: 0.24981946309293973

Emotion: realization
Ingroup Agree: 0.030217378412942975
Ingroup Disagree: 0.035147433984420565
Outgroup Agree: 0.029541275728174103
Outgroup Disagree: 0.03545683082032115

Emotion: disappointment
Ingroup Agree: 0.05747743113478702
Ingroup Disagree: 0.055113685419061864
Outgroup Agree: 0.04721524924254608
Outgroup Disagree: 0.06199614855482119

Emotion: disapproval
Ingroup Agree: 0.0566638478016536
Ingroup Disagree: 0.13129565253241424
Outgroup Agree: 0.0973441472644421
Outgroup Disagree: 0.1392985958750404

Emotion: optimism
Ingroup Agree: 0.05917445338783725
Ingroup Disagree: 0.04516023943779708
Outgroup Agree: 0.05518671485802071
Outgroup Disagree: 0.049072865822663604

Emotion: annoyance
Ingroup Agree: 0.044122500056572735
Ingroup Disagree: 0.057302407755324344
Outgroup Agree: 0.04736214816313677
Outgroup Disagree: 0.05658886873074202

Emotion: confusion
Ingroup Agree: 0.03984434494267134
Ingroup Disagree: 0.036235263994514724
Outgroup Agree: 0.04345854722938027
Outgroup Disagree: 0.04633392543529747

Emotion: sadness
Ingroup Agree: 0.027026983249798152
Ingroup Disagree: 0.0216503344987495
Outgroup Agree: 0.018227395207581445
Outgroup Disagree: 0.022241572545168946

Emotion: caring
Ingroup Agree: 0.023947394855688926
Ingroup Disagree: 0.020872427891241517
Outgroup Agree: 0.020917870401029187
Outgroup Disagree: 0.023503449013254386

Emotion: admiration
Ingroup Agree: 0.04560311283485294
Ingroup Disagree: 0.030449760412512544
Outgroup Agree: 0.038866871964724076
Outgroup Disagree: 0.02399070631479325

Emotion: desire
Ingroup Agree: 0.0435807168640011
Ingroup Disagree: 0.03398176626606068
Outgroup Agree: 0.04144879320180293
Outgroup Disagree: 0.03324627642353817

Emotion: relief
Ingroup Agree: 0.0032550887910839897
Ingroup Disagree: 0.0025559936851051223
Outgroup Agree: 0.0035773427913358097
Outgroup Disagree: 0.0024994293581152545

Emotion: nervousness
Ingroup Agree: 0.007213614902179879
Ingroup Disagree: 0.006485012994888635
Outgroup Agree: 0.004915490320582725
Outgroup Disagree: 0.0043450269778887276

Emotion: curiosity
Ingroup Agree: 0.06732002087932204
Ingroup Disagree: 0.046356434280927304
Outgroup Agree: 0.06584083549170627
Outgroup Disagree: 0.061854401862451225

Emotion: remorse
Ingroup Agree: 0.002650389128150314
Ingroup Disagree: 0.0021199264060053477
Outgroup Agree: 0.002168417044570628
Outgroup Disagree: 0.00286369976518267

Emotion: embarrassment
Ingroup Agree: 0.002790890345548159
Ingroup Disagree: 0.0025464467388603804
Outgroup Agree: 0.0019257500520184147
Outgroup Disagree: 0.0028307694834287574

Emotion: disgust
Ingroup Agree: 0.006603557309024521
Ingroup Disagree: 0.005662546858211514
Outgroup Agree: 0.005277345650505298
Outgroup Disagree: 0.0071384807789479565

Emotion: surprise
Ingroup Agree: 0.0026709824642717934
Ingroup Disagree: 0.0023837358319646735
Outgroup Agree: 0.005752697064430975
Outgroup Disagree: 0.003077814727804114

Emotion: fear
Ingroup Agree: 0.012289654255110595
Ingroup Disagree: 0.010175357684004566
Outgroup Agree: 0.009921763986678496
Outgroup Disagree: 0.006478042230239228

Emotion: anger
Ingroup Agree: 0.007261888025257668
Ingroup Disagree: 0.010302196437917794
Outgroup Agree: 0.008880356602131401
Outgroup Disagree: 0.00899235276685915

Emotion: joy
Ingroup Agree: 0.007170050666565825
Ingroup Disagree: 0.005542599595952287
Outgroup Agree: 0.012704848282073565
Outgroup Disagree: 0.004950972066014928

Emotion: love
Ingroup Agree: 0.008828000233827186
Ingroup Disagree: 0.008835462048679105
Outgroup Agree: 0.0066525880043146225
Outgroup Disagree: 0.004714633290845435

Emotion: excitement
Ingroup Agree: 0.004183029792976807
Ingroup Disagree: 0.003528404226864936
Outgroup Agree: 0.004326954650805803
Outgroup Disagree: 0.002666290357969096

Emotion: pride
Ingroup Agree: 0.0018752027071347033
Ingroup Disagree: 0.0012327083766515649
Outgroup Agree: 0.0015782830807222756
Outgroup Disagree: 0.0011246281967207195

Emotion: grief
Ingroup Agree: 0.0011207096548789027
Ingroup Disagree: 0.000945918770381205
Outgroup Agree: 0.0008945415895527199
Outgroup Disagree: 0.0009375389187732891

Emotion: amusement
Ingroup Agree: 0.003534392151793271
Ingroup Disagree: 0.0021461818898097333
Outgroup Agree: 0.002804808816061349
Outgroup Disagree: 0.003519427417622626

Emotion: gratitude
Ingroup Agree: 0.02313261046776661
Ingroup Disagree: 0.015295097300570583
Outgroup Agree: 0.03126828172123599
Outgroup Disagree: 0.013883504904841026

### Question asking

In [24]:
df[df["convo_turn"].apply(lambda x: "user" in x.lower())].pivot_table(index="treatment", values='question_flag')

                   question_flag
treatment
Ingroup Agree           0.101633
Ingroup Disagree        0.089938
Outgroup Agree          0.114661
Outgroup Disagree       0.128834

In [25]:
df[df["convo_turn"].apply(lambda x: "llm" in x.lower())].pivot_table(index="treatment", values='question_flag')

                   question_flag
treatment
Ingroup Agree           0.066061
Ingroup Disagree        0.216460
Outgroup Agree          0.062321
Outgroup Disagree       0.195518

### Gratitude usage

In [26]:
df[df["convo_turn"].apply(lambda x: "user" in x.lower())].pivot_table(index="treatment", values='gratitude_flag')

                   gratitude_flag
treatment
Ingroup Agree            0.022989
Ingroup Disagree         0.014615
Outgroup Agree           0.032516
Outgroup Disagree        0.013385

In [27]:
df[df["convo_turn"].apply(lambda x: "llm" in x.lower())].pivot_table(index="treatment", values='gratitude_flag')

                   gratitude_flag
treatment
Ingroup Agree            0.104242
Ingroup Disagree         0.176437
Outgroup Agree           0.137793
Outgroup Disagree        0.169188

### Hedge usage

In [38]:
df[df["convo_turn"].apply(lambda x: "user" in x.lower())].pivot_table(index="treatment", values='hedge_flag')

                   hedge_flag
treatment
Ingroup Agree        0.740472
Ingroup Disagree     0.762788
Outgroup Agree       0.748431
Outgroup Disagree    0.799777

In [37]:
df[df["convo_turn"].apply(lambda x: "llm" in x.lower())].pivot_table(index="treatment", values='hedge_flag')

                   hedge_flag
treatment
Ingroup Agree        0.987879
Ingroup Disagree     0.993236
Outgroup Agree       0.989708
Outgroup Disagree    0.998880

### Vader sentiment

In [39]:
df[df["convo_turn"].apply(lambda x: "user" in x.lower())].pivot_table(index="treatment", values='positive_polarity')

                   positive_polarity
treatment
Ingroup Agree               0.631579
Ingroup Disagree            0.541315
Outgroup Agree              0.618939
Outgroup Disagree           0.542666

In [40]:
df[df["convo_turn"].apply(lambda x: "llm" in x.lower())].pivot_table(index="treatment", values='positive_polarity')

                   positive_polarity
treatment
Ingroup Agree               0.921212
Ingroup Disagree            0.866967
Outgroup Agree              0.974843
Outgroup Disagree           0.885154

In [18]:
eval(df['pos_tag_counts'].iloc[0])

NameError: name 'Counter' is not defined

In [ ]:
df['pos_tags'] = df['clean_body'].apply(lambda x: pos_tag(word_tokenize(x, language='english')))